"""
PDF Tool - Markdown 轉 PDF
使用 Playwright 渲染 HTML 後轉 PDF（無需額外安裝）
"""
import asyncio
import markdown
from pathlib import Path
from playwright.async_api import async_playwright


class PDFTool:
    def __init__(self):
        self._playwright = None
        self._browser = None

    async def _ensure_browser(self):
        """確保瀏覽器已啟動"""
        if self._browser is None:
            self._playwright = await async_playwright().start()
            self._browser = await self._playwright.chromium.launch(headless=True)

    async def generate(self, markdown_content: str, output_path: str,
                       title: str = "Report") -> dict:
        """
        將 Markdown 轉換為 PDF

        Args:
            markdown_content: Markdown 文字內容
            output_path: PDF 輸出路徑
            title: 文件標題

        Returns:
            {success: bool, path: str, error?: str}
        """
        try:
            await self._ensure_browser()

            # Markdown → HTML
            html_content = markdown.markdown(
                markdown_content,
                extensions=['tables', 'fenced_code', 'toc', 'nl2br']
            )

            # 完整 HTML 模板（支援中文）
            full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{title}</title>
    <style>
        @page {{
            size: A4;
            margin: 2cm;
        }}
        body {{
            font-family: "Microsoft JhengHei", "PingFang TC", "Noto Sans TC",
                         "Source Han Sans TC", sans-serif;
            font-size: 12pt;
            line-height: 1.8;
            color: #333;
            max-width: 100%;
        }}
        h1 {{
            color: #1a1a1a;
            border-bottom: 3px solid #333;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        h2 {{
            color: #2a2a2a;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            margin-top: 1.5em;
        }}
        h3 {{
            color: #3a3a3a;
            margin-top: 1.2em;
        }}
        p {{
            margin: 0.8em 0;
            text-align: justify;
        }}
        ul, ol {{
            margin: 0.8em 0;
            padding-left: 2em;
        }}
        li {{
            margin: 0.3em 0;
        }}
        code {{
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: "Consolas", "Monaco", monospace;
            font-size: 0.9em;
        }}
        pre {{
            background: #f4f4f4;
            padding: 1em;
            border-radius: 5px;
            overflow-x: auto;
            border-left: 4px solid #666;
        }}
        pre code {{
            background: none;
            padding: 0;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 1em 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}
        th {{
            background: #f4f4f4;
            font-weight: bold;
        }}
        tr:nth-child(even) {{
            background: #fafafa;
        }}
        blockquote {{
            border-left: 4px solid #ccc;
            margin: 1em 0;
            padding: 0.5em 1em;
            background: #f9f9f9;
            color: #666;
        }}
        hr {{
            border: none;
            border-top: 1px solid #ccc;
            margin: 2em 0;
        }}
        a {{
            color: #0066cc;
            text-decoration: none;
        }}
        .footer {{
            position: fixed;
            bottom: 1cm;
            right: 1cm;
            font-size: 9pt;
            color: #999;
        }}
    </style>
</head>
<body>
    {html_content}
    <div class="footer">Generated by Monus</div>
</body>
</html>
"""

            # 使用 Playwright 渲染並轉 PDF
            page = await self._browser.new_page()
            await page.set_content(full_html, wait_until="networkidle")

            # 生成 PDF
            await page.pdf(
                path=output_path,
                format="A4",
                print_background=True,
                margin={
                    "top": "2cm",
                    "bottom": "2cm",
                    "left": "2cm",
                    "right": "2cm"
                }
            )

            await page.close()

            return {
                "success": True,
                "path": output_path
            }

        except Exception as e:
            return {
                "success": False,
                "path": output_path,
                "error": str(e)
            }

    async def from_file(self, markdown_path: str, output_path: str = None) -> dict:
        """從 Markdown 檔案生成 PDF"""
        md_path = Path(markdown_path)
        if not md_path.exists():
            return {"success": False, "error": f"File not found: {markdown_path}"}

        content = md_path.read_text(encoding="utf-8")
        output = output_path or str(md_path.with_suffix(".pdf"))

        return await self.generate(content, output, title=md_path.stem)

    async def close(self):
        """關閉瀏覽器"""
        if self._browser:
            await self._browser.close()
        if self._playwright:
            await self._playwright.stop()
        self._browser = None
        self._playwright = None


# 同步包裝器（方便直接調用）
def generate_pdf_sync(markdown_content: str, output_path: str, title: str = "Report") -> dict:
    """同步版本的 PDF 生成"""
    async def _run():
        tool = PDFTool()
        try:
            return await tool.generate(markdown_content, output_path, title)
        finally:
            await tool.close()

    return asyncio.run(_run())
