"""
Web Tool - Markdown 轉單頁網站
自包含 HTML + CSS，可直接分享
"""
import markdown
from pathlib import Path


class WebTool:
    def __init__(self):
        self.styles = ["article", "landing", "docs"]

    async def generate(self, markdown_content: str, output_path: str,
                       title: str = "Document", style: str = "article") -> dict:
        """
        將 Markdown 轉換為精美的單頁網站

        Args:
            markdown_content: Markdown 內容
            output_path: 輸出路徑 (.html)
            title: 頁面標題
            style: 樣式 (article/landing/docs)

        Returns:
            {success: bool, path: str, error?: str}
        """
        try:
            # Markdown 轉 HTML
            html_content = markdown.markdown(
                markdown_content,
                extensions=['tables', 'fenced_code', 'toc', 'nl2br', 'meta']
            )

            # 組合完整 HTML
            full_html = self._build_html(html_content, title, style)

            # 寫入檔案
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            Path(output_path).write_text(full_html, encoding='utf-8')

            return {
                "success": True,
                "path": output_path
            }

        except Exception as e:
            return {
                "success": False,
                "path": output_path,
                "error": str(e)
            }

    def _build_html(self, content: str, title: str, style: str) -> str:
        """建構完整的 HTML 頁面"""
        styles_map = {
            "article": self._article_css(),
            "landing": self._landing_css(),
            "docs": self._docs_css()
        }

        css = styles_map.get(style, styles_map["article"])

        return f'''<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{title}">
    <title>{title}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <style>
        {css}
    </style>
</head>
<body>
    <article class="container">
        {content}
    </article>
    <footer>
        <p>Generated by Monus</p>
    </footer>
    <script>
        hljs.highlightAll();

        // 平滑滾動
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {{
            anchor.addEventListener('click', function (e) {{
                e.preventDefault();
                document.querySelector(this.getAttribute('href')).scrollIntoView({{
                    behavior: 'smooth'
                }});
            }});
        }});
    </script>
</body>
</html>'''

    def _article_css(self) -> str:
        """文章閱讀風格 CSS"""
        return """
            :root {
                --bg: #fafafa;
                --text: #333;
                --accent: #0066cc;
                --border: #e0e0e0;
                --code-bg: #f4f4f4;
            }

            @media (prefers-color-scheme: dark) {
                :root {
                    --bg: #1a1a1a;
                    --text: #e0e0e0;
                    --accent: #5cacee;
                    --border: #333;
                    --code-bg: #2d2d2d;
                }
            }

            * { margin: 0; padding: 0; box-sizing: border-box; }

            body {
                font-family: "Microsoft JhengHei", "PingFang TC", "Noto Sans TC",
                             system-ui, -apple-system, sans-serif;
                background: var(--bg);
                color: var(--text);
                line-height: 1.8;
                font-size: 17px;
            }

            .container {
                max-width: 800px;
                margin: 0 auto;
                padding: 4rem 2rem;
            }

            h1 {
                font-size: 2.5rem;
                margin-bottom: 1rem;
                border-bottom: 3px solid var(--accent);
                padding-bottom: 0.5rem;
                line-height: 1.3;
            }

            h2 {
                font-size: 1.8rem;
                margin: 2.5rem 0 1rem;
                color: var(--accent);
                border-bottom: 1px solid var(--border);
                padding-bottom: 0.3rem;
            }

            h3 {
                font-size: 1.4rem;
                margin: 2rem 0 0.8rem;
            }

            h4 {
                font-size: 1.2rem;
                margin: 1.5rem 0 0.6rem;
            }

            p {
                margin: 1em 0;
                text-align: justify;
            }

            ul, ol {
                margin: 1em 0;
                padding-left: 2em;
            }

            li {
                margin: 0.5em 0;
            }

            pre {
                background: var(--code-bg);
                padding: 1.5em;
                border-radius: 8px;
                overflow-x: auto;
                margin: 1.5em 0;
                border-left: 4px solid var(--accent);
            }

            code {
                font-family: "Fira Code", "JetBrains Mono", Consolas, monospace;
                font-size: 0.9em;
            }

            :not(pre) > code {
                background: var(--code-bg);
                padding: 2px 6px;
                border-radius: 4px;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin: 1.5em 0;
                font-size: 0.95em;
            }

            th, td {
                border: 1px solid var(--border);
                padding: 0.8em;
                text-align: left;
            }

            th {
                background: var(--accent);
                color: white;
                font-weight: 600;
            }

            tr:nth-child(even) {
                background: rgba(0, 0, 0, 0.03);
            }

            blockquote {
                border-left: 4px solid var(--accent);
                margin: 1.5em 0;
                padding: 1em 1.5em;
                background: rgba(0, 102, 204, 0.05);
                border-radius: 0 8px 8px 0;
            }

            blockquote p {
                margin: 0;
            }

            a {
                color: var(--accent);
                text-decoration: none;
            }

            a:hover {
                text-decoration: underline;
            }

            img {
                max-width: 100%;
                height: auto;
                border-radius: 8px;
                margin: 1em 0;
            }

            hr {
                border: none;
                border-top: 1px solid var(--border);
                margin: 2.5em 0;
            }

            footer {
                text-align: center;
                padding: 2rem;
                color: #999;
                font-size: 0.9rem;
                border-top: 1px solid var(--border);
                margin-top: 4rem;
            }

            /* 響應式 */
            @media (max-width: 600px) {
                body { font-size: 16px; }
                .container { padding: 2rem 1rem; }
                h1 { font-size: 1.8rem; }
                h2 { font-size: 1.5rem; }
            }

            /* 列印樣式 */
            @media print {
                body { background: white; color: black; }
                .container { max-width: none; padding: 0; }
                footer { display: none; }
                pre { border-left-color: #333; }
            }
        """

    def _landing_css(self) -> str:
        """產品頁面風格 CSS"""
        return """
            :root {
                --bg: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                --text: #fff;
                --accent: #ffd700;
                --card-bg: rgba(255, 255, 255, 0.1);
            }

            * { margin: 0; padding: 0; box-sizing: border-box; }

            body {
                font-family: "Microsoft JhengHei", "PingFang TC", system-ui, sans-serif;
                background: var(--bg);
                color: var(--text);
                line-height: 1.8;
                min-height: 100vh;
            }

            .container {
                max-width: 1000px;
                margin: 0 auto;
                padding: 6rem 2rem;
                text-align: center;
            }

            h1 {
                font-size: 3.5rem;
                margin-bottom: 1.5rem;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            }

            h2 {
                font-size: 2rem;
                margin: 3rem 0 1.5rem;
                color: var(--accent);
            }

            h3 {
                font-size: 1.5rem;
                margin: 2rem 0 1rem;
            }

            p {
                font-size: 1.2rem;
                margin: 1em 0;
                max-width: 700px;
                margin-left: auto;
                margin-right: auto;
            }

            ul, ol {
                list-style: none;
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                gap: 1.5rem;
                margin: 2rem 0;
                padding: 0;
            }

            li {
                background: var(--card-bg);
                padding: 1.5rem 2rem;
                border-radius: 12px;
                backdrop-filter: blur(10px);
                min-width: 250px;
                text-align: left;
            }

            pre {
                background: rgba(0, 0, 0, 0.3);
                padding: 1.5em;
                border-radius: 12px;
                overflow-x: auto;
                margin: 2em auto;
                max-width: 800px;
                text-align: left;
            }

            code {
                font-family: "Fira Code", Consolas, monospace;
            }

            table {
                border-collapse: collapse;
                margin: 2em auto;
                background: var(--card-bg);
                border-radius: 12px;
                overflow: hidden;
            }

            th, td {
                padding: 1em 1.5em;
                text-align: left;
            }

            th {
                background: rgba(255, 255, 255, 0.2);
            }

            blockquote {
                background: var(--card-bg);
                padding: 2em;
                border-radius: 12px;
                margin: 2em auto;
                max-width: 700px;
                font-size: 1.3rem;
                font-style: italic;
            }

            a {
                color: var(--accent);
                text-decoration: none;
            }

            footer {
                padding: 2rem;
                color: rgba(255, 255, 255, 0.7);
                font-size: 0.9rem;
            }

            @media (max-width: 600px) {
                h1 { font-size: 2.2rem; }
                .container { padding: 3rem 1rem; }
                ul, ol { flex-direction: column; }
                li { min-width: auto; }
            }
        """

    def _docs_css(self) -> str:
        """技術文件風格 CSS"""
        return """
            :root {
                --bg: #ffffff;
                --sidebar-bg: #f8f9fa;
                --text: #24292e;
                --accent: #0366d6;
                --border: #e1e4e8;
                --code-bg: #f6f8fa;
            }

            * { margin: 0; padding: 0; box-sizing: border-box; }

            body {
                font-family: -apple-system, BlinkMacSystemFont, "Microsoft JhengHei",
                             "Segoe UI", Helvetica, Arial, sans-serif;
                background: var(--bg);
                color: var(--text);
                line-height: 1.7;
                font-size: 16px;
            }

            .container {
                max-width: 900px;
                margin: 0 auto;
                padding: 3rem 2rem;
            }

            h1 {
                font-size: 2.2rem;
                margin-bottom: 1rem;
                padding-bottom: 0.5rem;
                border-bottom: 1px solid var(--border);
            }

            h2 {
                font-size: 1.6rem;
                margin: 2rem 0 1rem;
                padding-bottom: 0.3rem;
                border-bottom: 1px solid var(--border);
            }

            h3 {
                font-size: 1.3rem;
                margin: 1.5rem 0 0.8rem;
            }

            h4 {
                font-size: 1.1rem;
                margin: 1.2rem 0 0.6rem;
            }

            p { margin: 1em 0; }

            ul, ol {
                margin: 1em 0;
                padding-left: 2em;
            }

            li { margin: 0.4em 0; }

            pre {
                background: var(--code-bg);
                padding: 1em;
                border-radius: 6px;
                overflow-x: auto;
                margin: 1em 0;
                border: 1px solid var(--border);
                font-size: 0.9em;
            }

            code {
                font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            }

            :not(pre) > code {
                background: var(--code-bg);
                padding: 0.2em 0.4em;
                border-radius: 3px;
                font-size: 0.9em;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin: 1em 0;
                font-size: 0.95em;
            }

            th, td {
                border: 1px solid var(--border);
                padding: 0.6em 1em;
                text-align: left;
            }

            th {
                background: var(--code-bg);
                font-weight: 600;
            }

            blockquote {
                border-left: 4px solid var(--accent);
                padding: 0.5em 1em;
                margin: 1em 0;
                background: var(--code-bg);
                color: #6a737d;
            }

            blockquote p { margin: 0; }

            a {
                color: var(--accent);
                text-decoration: none;
            }

            a:hover { text-decoration: underline; }

            hr {
                border: none;
                border-top: 1px solid var(--border);
                margin: 2em 0;
            }

            img {
                max-width: 100%;
                border: 1px solid var(--border);
                border-radius: 6px;
            }

            /* 提示框 */
            blockquote:has(strong:first-child) {
                border-left-color: #28a745;
                background: #f0fff4;
            }

            footer {
                text-align: center;
                padding: 2rem;
                color: #6a737d;
                font-size: 0.85rem;
                border-top: 1px solid var(--border);
                margin-top: 3rem;
            }

            @media (max-width: 600px) {
                .container { padding: 1.5rem 1rem; }
                h1 { font-size: 1.8rem; }
            }

            @media print {
                .container { max-width: none; }
                footer { display: none; }
            }
        """


# 同步包裝器
def generate_web_sync(markdown_content: str, output_path: str,
                      title: str = "Document", style: str = "article") -> dict:
    """同步版本的網頁生成"""
    import asyncio

    async def _run():
        tool = WebTool()
        return await tool.generate(markdown_content, output_path, title, style)

    return asyncio.run(_run())
